---
title: "Final Project"
output: html_document
date: "2023-11-13"
---

# Install and Load Packages
```{r}
library(readr)
library(dplyr)

```


# Importing Data
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#import secc urban dataset 
secc_urban <- read_csv("secc_cons_urban_shrid.csv")

#import secc rural dataset
secc_rural <- read_csv("secc_cons_rural_shrid.csv")

```


```{r}

library(ggplot2)
rural_shrid_caste <- read_csv("/Users/Juj/Downloads/shrug-secc-mord-rural-csv (1)/secc_rural_shrid.csv")

rural_consumption <- read_csv("/Users/Juj/Downloads/secc_cons_rural_shrid.csv")
                              
rural_merged <-  merge(rural_consumption, rural_shrid_caste, by = 'shrid2', all = FALSE)

urban_shrid_caste <- read_csv("/Users/Juj/Downloads/shrug-secc-parsed-urban-csv/secc_urban_shrid.csv")

urban_consumption <- read_csv("/Users/Juj/Downloads/secc_cons_urban_shrid.csv")
                              
urban_merged <-  merge(urban_consumption, urban_shrid_caste, by = 'shrid2', all = FALSE)



rural_merged %>%
  ggplot(mapping = aes(x = sc_share, y = secc_cons_pc_rural)) +
  geom_point(position = "jitter", alpha = .3) +
  geom_smooth() +
  scale_y_continuous(limits = c(NA, 150000)) +
  labs(x = "Share of Scheduled Caste Population in Rural Areas",
       y = "Per Capita Monthly Consumption") +
  theme_minimal()

urban_merged %>%
  ggplot(mapping = aes(x = sc_share, y = secc_cons_pc_urban)) +
  geom_point(position = "jitter", alpha = .3) +
  geom_smooth() +
  scale_y_continuous(limits = c(NA, 80000)) +
  labs(x = "Share of Scheduled Caste Population in Urban Areas",
       y = "Per Capita Monthly Consumption") +
  theme_minimal()



```

# Merging Data
```{r}

#secc urban and rural data-frames have different names, so can't do a vertical join. need to create a new dataframe with new column names, with an additional column to indicate urban/rural





```